---
- name: SSH hardening and Admin User Setup
  hosts: localhost
  become: yes
  vars:
    # default values
    admin_username: "tandica_admin"
    admin_groups: "wheel,it"
    ssh_key_path: "/home/tandi/.ssh/id_rsa.pub"
  tasks:
    - name: Add a new user
      user:
        name: "{{ admin_username }}"
        shell: /bin/bash
        groups: "{{ admin_groups }}"
        append: yes

    - name: Set up SSH key authentication
      authorized_key:
        user: "{{ admin_username }}"
        state: present
        key: "{{ lookup('file', ssh_key_path) }}"

    - name: Disable root login and password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        
    - name: Ensure SSH daemon reloads
      systemd:
        name: sshd
        state: restarted