---
- name: Check for unauthorized login attempts
  hosts: localhost
  become: yes
  tasks:
    - name: Check if /var/log/secure exists
      stat:
        path: /var/log/secure
      register: secure_log
      
    - name: Scan for failed login attempts
      shell: "grep 'password check failed for user' /var/log/secure | awk '{print $1, $2, $3, $11}' | sort -nr"
      register: failed_attempts_local
      when: secure_log.stat.exists

    - name: Scan for failed SSH login attempts
      shell: "grep 'Failed password' /var/log/secure | awk '{print $1, $2, $3, $9, $11}' | sort -nr"
      register: failed_attempts_ssh
      when: secure_log.stat.exists

    - name: Show failed user login attempts
      debug:
        msg: "{{ failed_attempts_local.stdout_lines }}"
      when: secure_log.stat.exists

    - name: Show failed user SSH login attempts
      debug:
        msg: "{{ failed_attempts_ssh.stdout_lines }}"
      when: secure_log.stat.exists

    - name: Show warning if /var/log/secure does not exist
      debug:
        msg: "/var/log/secure log file not found!"
      when: not secure_log.stat.exists
